apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-k8s-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: productak
    spec:
      containers:
      - name: sample-k8s-app-container
        image: akmaharshi.azurecr.io/akmaharshi/product-catalog-image:$BUILD_NUMBER
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: $KUBERNETES_SECRET_NAME
