apiVersion: apps/v1
kind: Deployment
metadata:
  name: productak
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: productak
    spec:
      containers:
      - name: productak
        image: akmaharshi.azurecr.io/akmaharshi/product-catalog-image:v9
        ports:
        - containerPort: 8282
      imagePullSecrets:
      - name: $KUBERNETES_SECRET_NAME
